package com.ai.gateway.adapter.postgresql;

import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 针对发布前单一数据库基线的静态守卫。
 *
 * <p>该测试有意不连接 PostgreSQL。它防止迁移目录在集成套件单独校验可执行 schema 的同时，
 * 悄无声息地回退为增量的 V2-V5 脚本。</p>
 *
 * @author cmiracle@163.com
 */
class GatewaySchemaMigrationTest {

    private static final String BASELINE = "/db/migration/V1__gateway_schema.sql";

    @Test
    void baselineContainsAllTablesAndNoRetiredMigrations() throws Exception {
        String sql = read(BASELINE);

        assertThat(Pattern.compile("(?im)^CREATE TABLE ").matcher(sql).results().count())
                .isEqualTo(15);
        assertThat(sql).doesNotContain("BIGSERIAL");
        assertThat(sql).contains("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        assertThat(sql).contains("operation_id UUID NOT NULL");
        assertThat(sql).contains("interaction_id UUID NOT NULL");
        assertThat(sql).contains("execution_id VARCHAR(128) NOT NULL");
        assertThat(sql).contains("CONSTRAINT uq_operation_record_idempotency_key UNIQUE (idempotency_key)");
        // 发起平面必须留在基线里：Confirm/Cancel 只能从操作记录读回平面，
        // 这一列消失并不会让任何测试报错，只会让写操作的终态审计静默退化为 unknown。
        assertThat(sql).contains("origin_plane VARCHAR(32)");
        assertThat(sql).contains("CREATE UNIQUE INDEX uq_snapshot_active_environment");
        assertThat(sql).contains("CONSTRAINT fk_outbox_audit_event FOREIGN KEY (audit_event_id)");
        assertThat(sql).contains("CREATE UNIQUE INDEX uq_audit_snapshot_lifecycle_event");
        assertThat(sql).contains("'MANIFEST_PUBLISHED', 'MANIFEST_SUSPENDED', 'CATALOG_ROLLED_BACK'");
        assertThat(sql).contains("CONSTRAINT uq_capability_manifest_business_key UNIQUE (id, version)");
        assertThat(sql).contains("CREATE TABLE acl_policy_epoch");
        assertThat(sql).contains("CHECK (policy_epoch > 0)");

        try (var files = Files.list(Path.of("src/main/resources/db/migration"))) {
            assertThat(files.filter(path -> path.toString().endsWith(".sql"))
                    .map(path -> path.getFileName().toString())
                    .toList()).containsExactly("V1__gateway_schema.sql");
        }
    }

    @Test
    void operationAndInteractionRepositoriesUseExplicitUuidCasts() throws Exception {
        String operationRepository = readClass(
                "/com/ai/gateway/adapter/postgresql/repository/JdbcOperationRepository.class");
        String interactionRepository = readClass(
                "/com/ai/gateway/adapter/postgresql/repository/JdbcInteractionRepository.class");

        // 类文件中以 UTF-8/modified UTF-8 字符串形式包含这些 SQL 常量。
        assertThat(operationRepository).contains("CAST(? AS UUID)");
        assertThat(interactionRepository).contains("CAST(? AS UUID)");
    }

    private static String read(String resource) throws Exception {
        try (var stream = GatewaySchemaMigrationTest.class.getResourceAsStream(resource)) {
            assertThat(stream).as("resource %s", resource).isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static String readClass(String resource) throws Exception {
        try (var stream = GatewaySchemaMigrationTest.class.getResourceAsStream(resource)) {
            assertThat(stream).as("resource %s", resource).isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.ISO_8859_1);
        }
    }
}
