package com.ai.gateway.adapter.postgresql;

import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Static guard for the pre-launch single database baseline.
 *
 * <p>This test intentionally does not connect to PostgreSQL.  It prevents the
 * migration directory from silently regressing to incremental V2-V5 scripts
 * while the integration suite validates the executable schema separately.</p>
 */
class GatewaySchemaMigrationTest {

    private static final String BASELINE = "/db/migration/V1__gateway_schema.sql";

    @Test
    void baselineContainsAllTablesAndNoRetiredMigrations() throws Exception {
        String sql = read(BASELINE);

        assertThat(Pattern.compile("(?im)^CREATE TABLE ").matcher(sql).results().count())
                .isEqualTo(14);
        assertThat(sql).doesNotContain("BIGSERIAL");
        assertThat(sql).contains("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        assertThat(sql).contains("operation_id UUID NOT NULL");
        assertThat(sql).contains("interaction_id UUID NOT NULL");
        assertThat(sql).contains("execution_id VARCHAR(128) NOT NULL");
        assertThat(sql).contains("CONSTRAINT uq_operation_record_idempotency_key UNIQUE (idempotency_key)");
        assertThat(sql).contains("CREATE UNIQUE INDEX uq_snapshot_active_environment");
        assertThat(sql).contains("CONSTRAINT fk_outbox_audit_event FOREIGN KEY (audit_event_id)");
        assertThat(sql).contains("CREATE UNIQUE INDEX uq_audit_snapshot_lifecycle_event");
        assertThat(sql).contains("'MANIFEST_PUBLISHED', 'MANIFEST_SUSPENDED', 'CATALOG_ROLLED_BACK'");
        assertThat(sql).contains("CONSTRAINT uq_capability_manifest_business_key UNIQUE (id, version)");

        try (var files = Files.list(Path.of("src/main/resources/db/migration"))) {
            assertThat(files.filter(path -> path.toString().endsWith(".sql"))
                    .map(path -> path.getFileName().toString())
                    .toList()).containsExactly("V1__gateway_schema.sql");
        }
    }

    @Test
    void operationAndInteractionRepositoriesUseExplicitUuidCasts() throws Exception {
        String operationRepository = readClass(
                "/com/ai/gateway/adapter/postgresql/repository/JdbcOperationRepository.class");
        String interactionRepository = readClass(
                "/com/ai/gateway/adapter/postgresql/repository/JdbcInteractionRepository.class");

        // Class files contain the SQL constants as UTF-8/modified UTF-8 strings.
        assertThat(operationRepository).contains("CAST(? AS UUID)");
        assertThat(interactionRepository).contains("CAST(? AS UUID)");
    }

    private static String read(String resource) throws Exception {
        try (var stream = GatewaySchemaMigrationTest.class.getResourceAsStream(resource)) {
            assertThat(stream).as("resource %s", resource).isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static String readClass(String resource) throws Exception {
        try (var stream = GatewaySchemaMigrationTest.class.getResourceAsStream(resource)) {
            assertThat(stream).as("resource %s", resource).isNotNull();
            return new String(stream.readAllBytes(), StandardCharsets.ISO_8859_1);
        }
    }
}
