package com.ai.gateway.domain.model;

import java.util.Map;

/**
 * Sealed interface representing the three possible decisions returned by
 * the LLM during natural-language routing.
 *
 * <p>Specifies that the model must return exactly one of three
 * decision types. The gateway uses short aliases (e.g.,
 * {@code cap_7k3m2v6p4a9d1f8q}) instead of raw capability IDs to avoid
 * function-name collisions, dot/colon issues, and length limits. The
 * alias-to-capability mapping is maintained per request:</p>
 *
 * <pre>
 * alias -&gt; capabilityId + capabilityVersion + manifestDigest
 * </pre>
 *
 * <p>The gateway performs deterministic checks after the model returns
 *:</p>
 * <ol>
 * <li>The selected alias belongs to this request's candidate set.</li>
 * <li>The current Principal still has permission.</li>
 * <li>The capability version is still executable.</li>
 * <li>Arguments satisfy the JSON Schema and business constraints.</li>
 * <li>All non-model parameters are injected from trusted sources.</li>
 * <li>The risk level permits the current execution mode.</li>
 * </ol>
 *
 * <p>The model must not declare authorization success or execution success.
 * Free-text reasons generated by the model are for UX only and are not used
 * as control-flow decisions.</p>
 *
 * @since 0.1.0
 */
public sealed interface ModelDecision
        permits ModelDecision.SelectDecision,
                ModelDecision.ClarifyDecision,
                ModelDecision.NoMatchDecision {

    /**
     * The model has selected a capability alias and provided MODEL arguments.
     *
     * <p>The gateway must verify that the alias belongs to the current
     * request's candidate set before proceeding. The
     * arguments are validated against the capability's public input
     * Schema.</p>
     *
     * @param alias the short alias identifying the selected capability
     * @param arguments the model-generated arguments as a JSON-compatible map
     */
    record SelectDecision(String alias, Map<String, Object> arguments)
            implements ModelDecision {

        /**
         * Compact constructor performing defensive copying.
         *
         * @param alias the capability alias
         * @param arguments the model arguments
         */
        public SelectDecision {
            java.util.Objects.requireNonNull(alias, "alias must not be null");
            java.util.Objects.requireNonNull(arguments, "arguments must not be null");
            arguments = Map.copyOf(arguments);
        }
    }

    /**
     * The model requests clarification from the user.
     *
     * <p>Defines the clarification session: the gateway stores
     * the candidate capability set, confirmed non-sensitive parameters,
     * and pending fields. Subsequent answers may only supplement missing
     * information or disambiguate within the original candidate set. If
     * the user abandons the original intent, the gateway must detect the
     * intent jump and restart the full routing pipeline.</p>
     *
     * @param question the clarification question to present to the user
     */
    record ClarifyDecision(String question)
            implements ModelDecision {

        /**
         * Compact constructor performing null check.
         *
         * @param question the clarification question
         */
        public ClarifyDecision {
            java.util.Objects.requireNonNull(question, "question must not be null");
        }
    }

    /**
     * The model determined that no capability in the candidate set matches
     * the user's request.
     *
     * <p>The gateway returns {@link ErrorCode#NO_CAPABILITY_MATCH} to the
     * caller. The reason code is for UX/logging only and is not used as
     * a control-flow decision.</p>
     *
     * @param reasonCode a stable reason code (e.g., {@code "NO_SUPPORTED_CAPABILITY"})
     */
    record NoMatchDecision(String reasonCode)
            implements ModelDecision {

        /**
         * Compact constructor performing null check.
         *
         * @param reasonCode the reason code
         */
        public NoMatchDecision {
            java.util.Objects.requireNonNull(reasonCode, "reasonCode must not be null");
        }
    }
}
