-- Gateway single baseline schema.
-- The project is not online yet: this script is the only schema migration and
-- is intended to be applied to an empty PostgreSQL database.
--
-- Every entity table has a monotonically increasing internal identity key.
-- External/business identifiers remain stable and are protected by UNIQUE
-- constraints.  Development databases must be dropped and recreated when the
-- baseline changes; V2-V5 and compatibility migrations are intentionally retired.

-- ---------------------------------------------------------------------------
-- Capability catalogue and lifecycle
-- ---------------------------------------------------------------------------
CREATE TABLE capability_manifest (
    manifest_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR(256) NOT NULL,
    version VARCHAR(32) NOT NULL,
    raw_content JSONB NOT NULL,
    sha256_digest VARCHAR(64) NOT NULL,
    owner_team VARCHAR(128) NOT NULL,
    owner_contact VARCHAR(256) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_capability_manifest_business_key UNIQUE (id, version)
);
CREATE INDEX idx_manifest_lifecycle ON capability_manifest(lifecycle);
CREATE INDEX idx_manifest_owner ON capability_manifest(owner_team);

CREATE TABLE capability_validation (
    validation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifest_id VARCHAR(256) NOT NULL,
    manifest_version VARCHAR(32) NOT NULL,
    report JSONB NOT NULL,
    validated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_capability_validation_manifest UNIQUE (manifest_id, manifest_version),
    CONSTRAINT fk_validation_manifest FOREIGN KEY (manifest_id, manifest_version)
        REFERENCES capability_manifest(id, version)
);

CREATE TABLE capability_approval (
    approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifest_id VARCHAR(256) NOT NULL,
    manifest_version VARCHAR(32) NOT NULL,
    approver VARCHAR(64) NOT NULL,
    role VARCHAR(64) NOT NULL,
    decision VARCHAR(16) NOT NULL,
    summary JSONB NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_capability_approval_manifest UNIQUE (manifest_id, manifest_version),
    CONSTRAINT fk_approval_manifest FOREIGN KEY (manifest_id, manifest_version)
        REFERENCES capability_manifest(id, version)
);

CREATE TABLE catalog_snapshot (
    snapshot_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    digest VARCHAR(64) NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_by VARCHAR(64) NOT NULL DEFAULT 'SYSTEM'
);
CREATE INDEX idx_snapshot_env_status ON catalog_snapshot(environment, status);
CREATE UNIQUE INDEX uq_snapshot_active_environment
    ON catalog_snapshot(environment)
    WHERE status = 'ACTIVE';

CREATE TABLE catalog_snapshot_item (
    snapshot_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_version BIGINT NOT NULL,
    capability_id VARCHAR(256) NOT NULL,
    capability_version VARCHAR(32) NOT NULL,
    manifest_digest VARCHAR(64) NOT NULL,
    policy_ref VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_snapshot_item_business_key
        UNIQUE (snapshot_version, capability_id, capability_version),
    CONSTRAINT fk_snapshot_item_snapshot FOREIGN KEY (snapshot_version)
        REFERENCES catalog_snapshot(snapshot_version),
    CONSTRAINT fk_snapshot_item_manifest FOREIGN KEY (capability_id, capability_version)
        REFERENCES capability_manifest(id, version)
);

-- ---------------------------------------------------------------------------
-- Runtime execution, write operations, audit and clarification sessions
-- ---------------------------------------------------------------------------
CREATE TABLE execution_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id VARCHAR(128) NOT NULL,
    principal_digest VARCHAR(64) NOT NULL,
    org_id BIGINT NOT NULL,
    capability_id VARCHAR(256) NOT NULL,
    capability_version VARCHAR(32) NOT NULL,
    snapshot_version BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    routing_summary JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_execution_record_execution_id UNIQUE (execution_id),
    CONSTRAINT fk_execution_snapshot FOREIGN KEY (snapshot_version)
        REFERENCES catalog_snapshot(snapshot_version)
);
CREATE INDEX idx_execution_status ON execution_record(status);
CREATE INDEX idx_execution_created_at ON execution_record(created_at);
CREATE INDEX idx_execution_capability_created
    ON execution_record(capability_id, created_at DESC);

CREATE TABLE operation_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id UUID NOT NULL,
    state VARCHAR(32) NOT NULL,
    principal_digest VARCHAR(64) NOT NULL,
    org_id BIGINT NOT NULL,
    capability_id VARCHAR(256) NOT NULL,
    capability_version VARCHAR(32) NOT NULL,
    manifest_digest VARCHAR(64) NOT NULL,
    snapshot_version BIGINT NOT NULL,
    encrypted_arguments TEXT,
    arguments_digest VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    policy_decision_id VARCHAR(64),
    confirmation_summary JSONB,
    expires_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    -- 发起 Prepare 的入口平面（AuditPlane 线上取值：gateway-nl / agent-host / mcp /
    -- a2a-inbound / structured / unknown）。Confirm/Cancel 是独立请求，其调用上下文无法
    -- 反映写操作最初来自哪个平面，不落库就只能在终态审计里省略平面标签，或一律按
    -- structured 归属——后者会把 MCP、A2A 发起的写操作错误计入结构化直调，污染成本归因。
    -- 刻意不设 DEFAULT：缺省值会让漏传平面的调用点静默通过，NULL 由应用层映射为 unknown。
    origin_plane VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_operation_record_operation_id UNIQUE (operation_id),
    CONSTRAINT uq_operation_record_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_operation_snapshot FOREIGN KEY (snapshot_version)
        REFERENCES catalog_snapshot(snapshot_version)
);
CREATE INDEX idx_operation_state ON operation_record(state);
CREATE INDEX idx_operation_expires_at ON operation_record(expires_at);

CREATE TABLE audit_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subject_digest VARCHAR(64),
    org_id BIGINT,
    request_id VARCHAR(128),
    operation_id VARCHAR(128),
    capability_id VARCHAR(256),
    capability_version VARCHAR(32),
    manifest_digest VARCHAR(64),
    snapshot_version BIGINT,
    policy_decision_id VARCHAR(64),
    model_prompt_version VARCHAR(64),
    result_code VARCHAR(64),
    duration_ms BIGINT,
    details JSONB
);
CREATE INDEX idx_audit_event_type ON audit_event(event_type);
CREATE INDEX idx_audit_timestamp ON audit_event(timestamp);
CREATE INDEX idx_audit_capability ON audit_event(capability_id);
CREATE INDEX idx_audit_request ON audit_event(request_id);
CREATE INDEX idx_audit_result_code ON audit_event(result_code);
CREATE INDEX idx_audit_operation ON audit_event(operation_id);
CREATE UNIQUE INDEX uq_audit_snapshot_lifecycle_event
    ON audit_event(snapshot_version, event_type)
    WHERE snapshot_version IS NOT NULL
      AND event_type IN ('MANIFEST_PUBLISHED', 'MANIFEST_SUSPENDED', 'CATALOG_ROLLED_BACK');

CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exported_at TIMESTAMPTZ,
    audit_event_id BIGINT,
    CONSTRAINT fk_outbox_audit_event FOREIGN KEY (audit_event_id)
        REFERENCES audit_event(event_id)
);
CREATE INDEX idx_outbox_status ON outbox_event(status);
CREATE INDEX idx_outbox_audit_event_id ON outbox_event(audit_event_id);

CREATE TABLE nl_interaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_id UUID NOT NULL,
    principal_digest VARCHAR(64) NOT NULL,
    snapshot_version BIGINT NOT NULL,
    candidates JSONB NOT NULL,
    confirmed_params JSONB,
    pending_fields JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_nl_interaction_interaction_id UNIQUE (interaction_id),
    CONSTRAINT fk_interaction_snapshot FOREIGN KEY (snapshot_version)
        REFERENCES catalog_snapshot(snapshot_version)
);
CREATE INDEX idx_interaction_expires ON nl_interaction(expires_at);

-- ---------------------------------------------------------------------------
-- ACL and console configuration
-- ---------------------------------------------------------------------------
CREATE TABLE gateway_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gateway_permission_name UNIQUE (name)
);

CREATE TABLE gateway_role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(512) NOT NULL DEFAULT '',
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gateway_role_name UNIQUE (name)
);

CREATE TABLE capability_acl (
    acl_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_id VARCHAR(256) NOT NULL,
    capability_version VARCHAR(32) NOT NULL,
    allowed_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
    required_permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(64) NOT NULL DEFAULT 'system',
    CONSTRAINT uq_capability_acl_business_key UNIQUE (capability_id, capability_version)
);

CREATE TABLE acl_policy_epoch (
    singleton_id SMALLINT PRIMARY KEY,
    policy_epoch BIGINT NOT NULL CHECK (policy_epoch > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_acl_policy_epoch_singleton CHECK (singleton_id = 1)
);
INSERT INTO acl_policy_epoch (singleton_id, policy_epoch) VALUES (1, 1);

CREATE TABLE console_setting (
    setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NOT NULL,
    description VARCHAR(512) NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(64) NOT NULL DEFAULT 'system',
    CONSTRAINT uq_console_setting_key UNIQUE (setting_key)
);

-- Seed the default roles required by the admin console.
INSERT INTO gateway_role (name, description, permissions) VALUES
    ('admin', 'Full administrative access',
     '["system:config:read","system:config:write","system:monitor:read","system:audit:read","capability:manifest:import","capability:manifest:approve","capability:release:publish","capability:release:rollback","capability:suspend:emergency","acl:role:manage","acl:permission:manage","acl:entry:manage"]'::jsonb),
    ('operator', 'Operational monitoring and management',
     '["system:config:read","system:monitor:read","system:audit:read"]'::jsonb),
    ('developer', 'Capability development and testing',
     '["system:capability:read","system:capability:write","capability:manifest:import"]'::jsonb);
